### ISSUE TITLE
[OpenCL] pocl seg-faults with some tests.

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#1319]
Apparently it is 2D CSR intergation which is used in medfilt1d but also in test_flat 2d:
```
INFO:pyFAI.test.test_flat:2D method:lut_ocl_cpu Imin=0.99999976 Imax=1.0000002 <I>=1.0 std=5.750552e-08
INFO:pyFAI.test.test_flat:About to test2d csr_ocl_cpu
INFO:pyFAI.azimuthalIntegrator:AI.integrate2d: Resetting integrator because init
INFO:silx.opencl.processing:37.751MB are needed on device: pthread-Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz,  which has 14656.508MB
WARNING:pyFAI.opencl.azim_csr:Please upgrade to silx v0.10+
INFO:silx.opencl.processing:Compiling file ['pyfai:openCL/kahan.cl', 'pyfai:openCL/preprocess.cl', 'pyfai:openCL/memset.cl', 'pyfai:openCL/ocl_azim_CSR.cl'] with options -D NBINS=180000  -D NIMAGE=307200 -D WORKGROUP_SIZE=64
DEBUG:pyopencl.cache:build program: binary cache miss (key: 8b22325a4d22a879e30e5301bbc65fbe)
DEBUG:pyopencl.cache:build program: start building program from source on <pyopencl.Device 'pthread-Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz' on 'Portable Computing Language' at 0x25953d0>
DEBUG:pyopencl.cache:build program: from-source build complete
Erreur de segmentation
```

**Comment by picca** [comment]
(sid_amd64-dchroot)picca@barriere:~/pyfai$ python3.7 ./run_tests.py pyFAI.test.test_flat -vv
INFO:root:Generating grammar tables from /usr/lib/python3.7/lib2to3/Grammar.txt
INFO:root:Generating grammar tables from /usr/lib/python3.7/lib2to3/PatternGrammar.txt
INFO:pyFAI.setup:Use setuptools
INFO:pyFAI.setup:Use setuptools.setup
WARNING:run_tests:Building pyFAI to /home/picca/pyfai/build/lib.linux-x86_64-3.7
INFO:root:Generating grammar tables from /usr/lib/python3.7/lib2to3/Grammar.txt
INFO:root:Generating grammar tables from /usr/lib/python3.7/lib2to3/PatternGrammar.txt
INFO:pyFAI.setup:Use setuptools
INFO:pyFAI.setup:Install requires: numpy >=1.17.4
running build
running build_py
running build_ext
WARNING:run_tests:Patched sys.path, added: '/home/picca/pyfai/build/lib.linux-x86_64-3.7'
WARNING:run_tests:Test pyFAI 0.19.0 from /home/picca/pyfai/build/lib.linux-x86_64-3.7/pyFAI
DEBUG:pyFAI.ext.splitBBoxLUT:LUT sizes C:8 	 Numpy: 8
INFO:pyFAI.method_registry:Degrading method from Method(dim=1, split='pseudo', algo='histogram', impl='*', target=None) -> Method(dim=1, split='bbox', algo='histogram', impl='*', target=None)
INFO:pyFAI.method_registry:Degrading method from Method(dim=2, split='full', algo='histogram', impl='*', target=None) -> Method(dim=2, split='pseudo', algo='histogram', impl='*', target=None)
test_correct (pyFAI.test.test_flat.TestFlat1D) ... DEBUG:pyFAI.DEPRECATION:Function _integrate1d_legacy is deprecated since pyFAI version 0.20.
  File "/home/picca/pyfai/build/lib.linux-x86_64-3.7/pyFAI/test/test_flat.py", line 91, in test_correct
    _, I = self.ai.integrate1d(self.raw, self.bins, unit="r_mm", method=meth, correctSolidAngle=False, dark=self.dark, flat=self.flat)
DEBUG:pyFAI.azimuthalIntegrator:integrate1d uses Numpy implementation
INFO:pyFAI.test.test_flat:1D method:numpy Imin=1.0 Imax=1.0 <I>=1.0 std=0.0
DEBUG:pyFAI.azimuthalIntegrator:integrate1d uses cython implementation
INFO:pyFAI.test.test_flat:1D method:cython Imin=0.99999994 Imax=1.0 <I>=1.0 std=2.6656009e-09
DEBUG:pyFAI.azimuthalIntegrator:integrate1d uses BBox implementation
INFO:pyFAI.test.test_flat:1D method:splitbbox Imin=1.0 Imax=1.0000001 <I>=1.0 std=5.3312017e-09
DEBUG:pyFAI.azimuthalIntegrator:integrate1d uses Numpy implementation
INFO:pyFAI.test.test_flat:1D method:splitpix Imin=1.0 Imax=1.0 <I>=1.0 std=0.0
INFO:pyFAI.azimuthalIntegrator:AI.integrate1d: Resetting integrator because init
INFO:pyFAI.test.test_flat:1D method:lut Imin=0.99999994 Imax=1.0 <I>=1.0 std=2.6656009e-09
INFO:pyFAI.azimuthalIntegrator:AI.integrate1d: Resetting integrator because init
INFO:pyFAI.test.test_flat:1D method:csr Imin=1.0 Imax=1.0000001 <I>=1.0 std=5.3312017e-09
INFO:silx.opencl.processing:25.113MB are needed on device: pthread-Intel(R) Xeon(R) CPU E5-2640 v2 @ 2.00GHz,  which has 6218.457MB
INFO:silx.opencl.processing:Compiling file ['pyfai:openCL/kahan.cl', 'pyfai:openCL/preprocess.cl', 'pyfai:openCL/memset.cl', 'pyfai:openCL/ocl_azim_LUT.cl'] with options -D NBINS=500  -D NIMAGE=307200 -D NLUT=3128 -D ON_CPU=1
DEBUG:pyopencl.cache:build program: binary cache hit (key: b50be999329bc093d0fa7bcdd7414086)
DEBUG:pytools.persistent_dict:pyopencl-invoker-cache-v6: disk cache hit [key=34c866820b98eb255143c7b7dcfaeda45f9172a2b25499aa161bc3c85fa8b549]
WARNING:py.warnings:/usr/lib/python3/dist-packages/pytools/py_codegen.py:26: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp

DEBUG:pytools.persistent_dict:pyopencl-invoker-cache-v6: disk cache hit [key=fd180fbe9be5bdff93ea98a6b947994467353acfc89d6602203e5b63e3850b86]
DEBUG:pytools.persistent_dict:pyopencl-invoker-cache-v6: disk cache hit [key=adc4e49acde32404e18f4b3c6f052f0cb4d55afeedcc29dcc6d4b93546716a5b]
DEBUG:pytools.persistent_dict:pyopencl-invoker-cache-v6: disk cache hit [key=2f111d2d34ddbe3c68f5e43f97ed2dd391e780379a13019793886d2ff050dcb0]
DEBUG:pytools.persistent_dict:pyopencl-invoker-cache-v6: disk cache hit [key=99a6ae56869804d7cfc7885bcbcc204dfdd10713d36997f07ae0f5ccbc98effe]
DEBUG:pytools.persistent_dict:pyopencl-invoker-cache-v6: disk cache hit [key=46fb8e54cbc85092a51d39114ffa317430e0dd646f2933dfacd657256c4369d3]
DEBUG:pytools.persistent_dict:pyopencl-invoker-cache-v6: disk cache hit [key=3108a82a04b26eb2b7daf35c7e8a4c6a7e8efe49fc4fc703df0cf30f03fbfa46]
DEBUG:pytools.persistent_dict:pyopencl-invoker-cache-v6: disk cache hit [key=1f25ef7e8cd790a16cb08a784b324cba77999ac65bae40a5027342047018a081]
DEBUG:pytools.persistent_dict:pyopencl-invoker-cache-v6: disk cache hit [key=fd615a2bc4b829648ac1ac01dd10387621de1ee3860e5b8eec82983f61e9eb93]
DEBUG:pytools.persistent_dict:pyopencl-invoker-cache-v6: disk cache hit [key=24870004e6c7e414630dcba07d026c149169dfcc918b6cb2ceebe054cf8ba0fa]
DEBUG:pytools.persistent_dict:pyopencl-invoker-cache-v6: disk cache hit [key=56948684b3acdf1af53d8b5bfbfc8d082b8af924cbb04d57cf076477daf7ca83]
DEBUG:pytools.persistent_dict:pyopencl-invoker-cache-v6: disk cache hit [key=9dfdb0d073b70ef1e5436322c8387e859ad3b7093faaa2f5904d13820026c091]
DEBUG:pytools.persistent_dict:pyopencl-invoker-cache-v6: disk cache hit [key=92c1165f83c799e7a85c1b3c61aba9e624a623b8714cb4828c02f0bba6dcc4aa]
DEBUG:pytools.persistent_dict:pyopencl-invoker-cache-v6: disk cache hit [key=42e72677b6ae1fcf1e36ba6a40ba69f4eb2bf5285e18a68b9710fcfa7449b3cc]
DEBUG:pytools.persistent_dict:pyopencl-invoker-cache-v6: disk cache hit [key=d98358a03b4210f83faea122b184ab9f0be1249a8767cbc098bb13737fb1a43f]
DEBUG:pytools.persistent_dict:pyopencl-invoker-cache-v6: disk cache hit [key=9a81dc7154bc268246a0787c41d8941a50048439436db81ac7b3e3bab545c095]
DEBUG:pytools.persistent_dict:pyopencl-invoker-cache-v6: disk cache hit [key=cf2a2747a61a4dc2c2d20ffa85231a4cb62273dd58da573ad447f4c71ba5553d]
DEBUG:pytools.persistent_dict:pyopencl-invoker-cache-v6: disk cache hit [key=a59344e5997041e2fee2fd91538f4c0fb00fd0d7a02db9365e92d8c8fe6531b3]
INFO:pyFAI.test.test_flat:1D method:lut_ocl_cpu Imin=0.99999994 Imax=1.0000001 <I>=1.0 std=2.7957057e-08
INFO:silx.opencl.processing:23.969MB are needed on device: pthread-Intel(R) Xeon(R) CPU E5-2640 v2 @ 2.00GHz,  which has 6218.457MB
INFO:silx.opencl.processing:Compiling file ['pyfai:openCL/kahan.cl', 'pyfai:openCL/preprocess.cl', 'pyfai:openCL/memset.cl', 'pyfai:openCL/ocl_azim_CSR.cl'] with options -D NBINS=500  -D NIMAGE=307200 -D WORKGROUP_SIZE=32
DEBUG:pyopencl.cache:build program: binary cache miss (key: 2050aa11c63ca8ba273251f7e157c472)
DEBUG:pyopencl.cache:build program: start building program from source on <pyopencl.Device 'pthread-Intel(R) Xeon(R) CPU E5-2640 v2 @ 2.00GHz' on 'Portable Computing Language' at 0x2bbb8e0>
DEBUG:pyopencl.cache:build program: from-source build complete
[barriere:29844] *** Process received signal ***
[barriere:29844] Signal: Segmentation fault (11)
[barriere:29844] Signal code: Address not mapped (1)
[barriere:29844] Failing at address: 0x28
[barriere:29844] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x3a100)[0x7f5cb476a100]
[barriere:29844] [ 1] /usr/lib/x86_64-linux-gnu/libLLVM-8.so.1(+0x17f4ba2)[0x7f5c9dac8ba2]
[barriere:29844] [ 2] /usr/lib/x86_64-linux-gnu/libLLVM-8.so.1(+0x17e7e87)[0x7f5c9dabbe87]
[barriere:29844] [ 3] /usr/lib/x86_64-linux-gnu/libLLVM-8.so.1(+0x17f4de0)[0x7f5c9dac8de0]
[barriere:29844] [ 4] /usr/lib/x86_64-linux-gnu/libLLVM-8.so.1(+0x17e7e87)[0x7f5c9dabbe87]
[barriere:29844] [ 5] /usr/lib/x86_64-linux-gnu/libLLVM-8.so.1(+0x17f643b)[0x7f5c9daca43b]
[barriere:29844] [ 6] /usr/lib/x86_64-linux-gnu/libLLVM-8.so.1(+0x17e7e87)[0x7f5c9dabbe87]
[barriere:29844] [ 7] /usr/lib/x86_64-linux-gnu/libLLVM-8.so.1(_ZN4llvm16computeKnownBitsEPKNS_5ValueERKNS_10DataLayoutEjPNS_15AssumptionCacheEPKNS_11InstructionEPKNS_13DominatorTreeEPNS_25OptimizationRemarkEmitterEb+0xeb)[0x7f5c9dabc18b]
[barriere:29844] [ 8] /usr/lib/x86_64-linux-gnu/libLLVM-8.so.1(_ZN4llvm26getOrEnforceKnownAlignmentEPNS_5ValueEjRKNS_10DataLayoutEPKNS_11InstructionEPNS_15AssumptionCacheEPKNS_13DominatorTreeE+0x36)[0x7f5c9d492046]
[barriere:29844] [ 9] /usr/lib/x86_64-linux-gnu/libLLVM-8.so.1(+0x13338a4)[0x7f5c9d6078a4]
[barriere:29844] [10] /usr/lib/x86_64-linux-gnu/libLLVM-8.so.1(+0x12d1b8c)[0x7f5c9d5a5b8c]
[barriere:29844] [11] /usr/lib/x86_64-linux-gnu/libLLVM-8.so.1(+0x12d3106)[0x7f5c9d5a7106]
[barriere:29844] [12] /usr/lib/x86_64-linux-gnu/libLLVM-8.so.1(_ZN4llvm24InstructionCombiningPass13runOnFunctionERNS_8FunctionE+0x1ff)[0x7f5c9d5a74bf]
[barriere:29844] [13] /usr/lib/x86_64-linux-gnu/libLLVM-8.so.1(_ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE+0x3f0)[0x7f5c9ce61400]
[barriere:29844] [14] /usr/lib/x86_64-linux-gnu/libLLVM-8.so.1(_ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE+0x33)[0x7f5c9ce61673]
[barriere:29844] [15] /usr/lib/x86_64-linux-gnu/libLLVM-8.so.1(_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE+0x2ee)[0x7f5c9ce61a3e]
[barriere:29844] [16] /usr/lib/x86_64-linux-gnu/libpocl.so.2.4.0(+0x2a26fc)[0x7f5ca6b066fc]
[barriere:29844] [17] /usr/lib/x86_64-linux-gnu/libpocl.so.2.4.0(+0x2492e9)[0x7f5ca6aad2e9]
[barriere:29844] [18] /usr/lib/x86_64-linux-gnu/libpocl.so.2.4.0(+0x24b923)[0x7f5ca6aaf923]
[barriere:29844] [19] /usr/lib/x86_64-linux-gnu/libpocl.so.2.4.0(+0x24bf93)[0x7f5ca6aaff93]
[barriere:29844] [20] /usr/lib/x86_64-linux-gnu/libpocl.so.2.4.0(+0x21bb91)[0x7f5ca6a7fb91]
[barriere:29844] [21] /usr/lib/x86_64-linux-gnu/libpocl.so.2.4.0(+0x22fafc)[0x7f5ca6a93afc]
[barriere:29844] [22] /usr/lib/python3/dist-packages/pyopencl/_cl.cpython-37m-x86_64-linux-gnu.so(+0x9c385)[0x7f5ca7f2a385]
[barriere:29844] [23] /usr/lib/python3/dist-packages/pyopencl/_cl.cpython-37m-x86_64-linux-gnu.so(+0xb76c6)[0x7f5ca7f456c6]
[barriere:29844] [24] /usr/lib/python3/dist-packages/pyopencl/_cl.cpython-37m-x86_64-linux-gnu.so(+0x41917)[0x7f5ca7ecf917]
[barriere:29844] [25] python3.7(_PyMethodDef_RawFastCallKeywords+0x13b)[0x5cc06b]
[barriere:29844] [26] python3.7(_PyObject_FastCallKeywords+0x6c9)[0x5cd469]
[barriere:29844] [27] python3.7[0x538c71]
[barriere:29844] [28] python3.7(_PyEval_EvalFrameDefault+0x4557)[0x53f8e7]
[barriere:29844] [29] python3.7(_PyEval_EvalCodeWithName+0xb78)[0x53a178]
[barriere:29844] *** End of error message ***
Segmentation fault
