### ISSUE TITLE
units of detector.set_dx()

### ISSUE THREAD

**Issue by CPrescher** [silx-kit/pyFAI#1377]
Hi,

I have a short question about the distortion definition in pyFAI. 
I try to perform some parallax correction automatically during calibration by offsetting all the pixels based on their two-theta value a bit. I always thought the set_dx function would take pixel value offsets. But my current results indicate, that it is rather um offsets? Could you please clarify?
The function description says pixel-wise, which is not exactly clear to me because it could also just mean distortion per pixel.

Best wishes, 
Clemens

**Comment by kif** [comment]
Hi Clemens, 
As I commented in 1378, this `set_dx` and `set_dy` are hardly used. They have been superseded by the pixel_corner_array.

I agree this is not documented at all.

For Pilatus detectors, this is in percent of a pixel (not intuitive, I agree), because they want the data to be saved as integers.
But for the general case, this is fraction of a pixel.

This is mostly used with array of size equals to the  size of the detector +1. The +1 is because we work on edges and not on pixel centre. In this case it represents the displacement in fraction of pixel. 

By re-reading the code, I noticed that your use-case is with the dx.shape=detector.shape, for which I cannot remember any use-case. This is probably dead-code as `dx` and `dy` are never used or saved in HDF5. 
The easiest would be to fall-back on the pixel-corner array; knowing that there will be overlaying fractions of pixels.

**Comment by CPrescher** [comment]
Hm, what does the integration algorithm do when the pixels are overlaying? 
Does this mean, it would be better to manually calculate the pixel_corners array? (with non overlapping pixels?)

**Comment by kif** [comment]
On Wed, 15 Jul 2020 07:23:13 -0700
Clemens Prescher <notifications@github.com> wrote:

> Hm, what does the integration algorithm do when the pixels are overlaying? 

It should work as expected: there is no notion of shadow between pixel (yet?)

> Does this mean, it would be better to manually calculate the pixel_corners array? (with non overlapping pixels?)

Definitely.
Calculate the position of the edges and there is a function to calculate the 4D array automatically.


Just for curiosity, what kind of detector are you trying to calibrate ? 

Cheers,

**Comment by CPrescher** [comment]
Hi,

thanks, I will have a look into calculating myself.
We have issues with the Perkin Elmer and Varex detectors. The line positions just do not match the calibrant after refining the geometry. Those detectors have very thick layers so parallax might be a big issue here. 

Best wishes,
Clemens

**Comment by kif** [comment]
I wrote a tutorial on correcting parallax issue (not simple). Maybe it is worth to deconvolute those images for parallax before distortion correction. The MLEM method is working decently (but not perfectly: noise raises).

I advocate for calibrating the detector's geometry independently from the diffraction setup, but you need a fine grid and parallel, uniform beam. There are plenty of tutorials on this. Once calibrated, just save the detector definition as HDF5.

**Comment by CPrescher** [comment]
Hi, do you mean the "thick detectors" tutorials in the pyFAI documentation? I have to work through them still.

Sure, it is good to calibrate the detector having a holeplate. We actually made one of the size of these detectors (which are quite big). First of all it was hard to make it, but we finally found, that acid edging is the best method with very good precision of the hole positions. The issue for correcting parallax effect from just a diffraction experiment (e.g. a glass) with a hole plate comes here now from actually exactly knowing the distance and tilt/rotation of the holeplate to the detector distance. I have to try to estimate it, which I think is actually correcting for a parallax effect seen on the detector...
Thus, I think that the distortions seen with this method are not circular but real detector and holeplate distortions.

For all of those large detectors, I actually found that just letting the wavelength vary during the calibration can correct for the peak shifts, but beamline scientist do not like this, because they know their wavelength and are afraid of errors from this "correction" method.

**Comment by kif** [comment]
re-open if needed.
