### ISSUE TITLE
Issues about the documentation

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#1418]
We discussed with @loichuder @takluyver and found those issues in the documentation:
- [x] Start the documentation with a sketch of the transformation performed within pyFAI
- [x] Remove the video from the main page (-> to the publication sections ?)
- [x] Switch the default theme to the RTD one (at least it looks consistent between RTD and silx.org)
- [x] Put forward the scheme with the geometry and what the poni-file is (i.e. the file containing the geometry)
- [x] Definition of the poni-file in the glossary, link to the proper section
- [x] Restructure `cookbooks` and include them within `tutorials`, maybe as `HowTos`
- [x] Provide video for the cookbooks explaining how to use the GUI applications (<5mn)
- [x] Expose the 5 layers of pyFAI and link the API doc from there.  
- [x] Label explicitly deprecated scripts.
- [x] Do not document apps in the API doc, but Nexus is missing for example.
- [x] Link the documentation from the readme file (use badges?)

**Comment by kif** [comment]
Attempt for the first sketch:
![overview](https://user-images.githubusercontent.com/1018880/97465636-8849b580-1942-11eb-9239-64652b9bbd9f.png)

**Comment by loichuder** [comment]
Looks good ! I would perhaps make the arrows start from the 2D diffraction pattern (above PyFAI).

**Comment by takluyver** [comment]
Thoughts on the image:

- I agree with Loïc - it could be clearer that the top image is input.
- It's not immediately obvious what the 3D image is showing. Peering closely, I think I can see that the detector image is tilted within the axes box. But I'm not sure how I'd make use of that transformation apart from looking at a 3D view. Maybe there's a better way to illustrate what's going on? Or maybe it's better to leave this out?
- It's not very obvious that the bottom image is a transformation of the top one. Can we make the colour scales match closer? And maybe lose the overlaid green lines, so the lines in the image itself are more visible?
- I think the Wordart style 3D text looks kind of 1990s. But if you're happy with that look, don't let me put you off. :wink:

**Comment by kif** [comment]
For the 3D setup view, I am neither happy ... maybe we should find something else...
https://github.com/silx-kit/pyFAI/blob/c29764b040ae8bb1e6b04c3697713d17ce8f18b7/doc/source/img/overview.png?raw=true
About the Wordart ... sorry, I am an old guy, back from that time :-þ

**Comment by kif** [comment]
Could you please have a look at the upgraded documentation ?
https://pyfai--1419.org.readthedocs.build/en/1419/

Thanks

**Comment by loichuder** [comment]
My thoughts:

- I liked the fact that **PyFAI** laid on the arrow to show that it was doing the work. But I find this layout fine as well.
- Not a fan of the subtitle _space-folder_. I find the paragraph explaining it is a bit out-of-place (very specific and a bit hard to understand) given it is the landing page of the doc. Do you feel this subtitle adds needed information ?
- The paragraph before the PONI picture could be better. I think explaining **why** geometry and calibration are important and **why** this picture is important (i.e.  the beam and the detector could be misaligned) could be a huge gain.
- Not much but I think the arrow would look better if not biased and with the text aligned below. A small image to show you what I mean:
![pyFAI_arrow](https://user-images.githubusercontent.com/42204205/104482040-bf854580-55c6-11eb-9247-b79f1876acbe.png)

**Comment by kif** [comment]
And what about that:
https://pyfai--1450.org.readthedocs.build/en/1450/

**Comment by loichuder** [comment]
Much better :+1: !

I still have a few proposals:
- I would remove the **of pyFAI** and **to pyFAI** of the headers since we are already in the pyFAI doc.
- The **Example of usage** section should be removed to keep **Cookbooks** and ** Tutorials** as first class sections as they are (to me) some of the most interesting sections of the doc. The text of the **Example of usage** section can be kept as intro of the sections in question.
- I would add a code block at the very beginning of **Installation** as a TL;DR: 
```
pip install pyFAI [--user]
```
and remove the **Abstract** subsection. Also, I would move this section up in the hierarchy. I think it should be one of the first.
- Missing **s** to **Publication**

If you agree on the changes above, I can implement them in a PR to help you :wink:

**Comment by takluyver** [comment]
I think the landing page in #1450 is a really nice improvement. The diagram really helps with understanding it. I also agree with most of what @loichuder suggests. I'll add that since pip 20.0, almost a year ago, pip automatically does a user install when necessary, so you shouldn't need to pass `--user` - but of course, you may still want to mention it, as there may be people with older versions of pip.

In terms of organisation, I'd love to see something like [this cookbook page](https://pyfai--1450.org.readthedocs.build/en/1450/usage/cookbook/integration_with_python.html) or [this tutorial section](https://pyfai--1450.org.readthedocs.build/en/1450/usage/tutorial/Introduction/introduction.html#Introduction-to-diffraction-image-analysis-using-the-notebook) given more prominence. Perhaps I'm not the main kind of user you're aiming at, but for me the Python interface is the most interesting piece, and at present it's kind of buried in the docs amongst the descriptions of command-line & GUI workflows.

Now that there's an introduction on the landing page, I wonder if it also makes sense to demote the 'General introduction' chapter, or work it in with something like the 'design of the library' chapter? It looks like valuable info, but I think people learn better from concrete examples than abstract descriptions.

**Comment by kif** [comment]
I merged #1450. Thanks for your contributions. 

The remaining issue is that you wish to see cookbooks and tutorials emphasized. 

I'll give a tutorial in a couple of weeks and the trainees may have suggestions as well.
