### ISSUE TITLE
[Request] How to build a poni file

### ISSUE THREAD

**Issue by alexmarie78** [silx-kit/pyFAI#1457]
Hello,

in a lot of your tutorials, you are using an already generated poni file, to instanciate a detector.
I would like to do the same, but I can't seem to find what is the strucure of a poni file.
Is there any tutorial or poni example file available ?

Thanks in advance for your response.

**Comment by RGBYCP** [comment]
Hi,
You get a poni file when you do the calibration of a detector with a calibrant with pyFAI-calib. 
My poni files contain:

Detector:
PixelSize1:
PixelSize2:
Distance: 
Poni1:
Poni2:
Rot1:
Rot2:
Rot3:
Wavelength:

HTH

**Comment by kif** [comment]
Hi,
The structure provided by @RGBYCP is correct and corresponds to the first version of the PONI-file.
All values are in SI-units, which means meters and radians. Probably not the most user friendly ones, but 
there are technical reasons for this. One advantage is that people will not fiddle too much with those floating point numbers.

Many PONI-files are used in the test suite and can be downloaded from there.
http://www.silx.org/pub/pyFAI/testimages/

Last information, the format is changing with a version 2 of the format which dropped pixel-size and splinefile information but gained a detector_config JSON-serialized. Both are inter-changeable but HDF5-definied detectors are not compatible with the version1.

In order to ensure a maximum compatibility, I would advice you to use the class in charge of it ...
http://www.silx.org/doc/pyFAI/dev/api/io/index.html#module-pyFAI.io.ponifile

**Comment by alexmarie78** [comment]
Thanks a lot, both of you, I will try with the two methods.
