### ISSUE TITLE
Errorbars for calibration parameters?

### ISSUE THREAD

**Issue by CPrescher** [silx-kit/pyFAI#154]
Hei there, 

i have a short questions. Some of my users have asked if it would be possible to give error bars on the calibration parameters? Is it possible to implement this into pyFAI? i have seen you use fmin_slsqp for calculating the parameters, which seems to have no covariance or hessian as output. 
Did you play with several optimization methods and this was the best? Or is there any other reason to use fmin_slsqp.

Clemens

**Comment by rififi** [comment]
Hi, I know the issue is close, but I've been looking for a solution foe several days. @kif , you said it is possible to recalculate the covariance matrix (fmin_slsqp does not output one). Do you have an idea about how to do that ?

**Comment by kif** [comment]
On Tue, 24 Mar 2015 02:59:43 -0700
rififi <notifications@github.com> wrote:

> Hi, I know the issue is close, but I've been looking for a solution foe several days. @kif , you said it is possible to recalculate the covariance matrix (fmin_slsqp does not output one). Do you have an idea about how to do that ?

Hi,

I like fmin_slsqp because of its robustness. But it is probably not the
best optimizer, especially next to the solution. As fmin_slsqp does not
provide the variance-covariance array, I used another
Levenberg-Marquard to measure the error next to the solution, and found
they were huge. 

Then I digged quite a bit and discovered the the answer was much more
complicated: it depends actually a lot on how many control points and
how they are exctracted. Some methods use Monte-Carlo sampling which
makes the result "unpredictible" while nicer for statistics. Since
recently one can extract all local maxima as control point. Lets'
assume we have all signal coming from every single grain in the sample
able to diffract.

The minimization is basically a refinement of the parameter set on the
sum of errors (squared). I calculated the hessian of this function,
which describes the curvature of the "model" around the minimum. What
is funny (or not), is that 
* distance and wavelength
* poni1 and rot2
* poni2 and rot1
are heavily correlated. So if you fix wavelength, rot1, rot2, rot3 you
get pretty good accuracy on distance and center (few �m on the center,
<1mm on the distance). But if you free all parameters, the confidence
interval is poor but the error is lower.

If one wants to play with this: it is implemented into the
GeometryRefinement class. The two methods of interest are:
def curve_fit(self, with_rot=True):
def confidence(self, with_rot=True):
To try them: install python-rfoo, perform the calibration as usual,
then connect to the process using rconsole (or rfoo-rconsole under
debian) the GeometryRefinement is in c.geoRef. Enjoy the hacking.

Anyway I am interested about the subject as I am far from an expert in
statistics and cross validation is never a bad idea.

Cheers,

-- 
J�r�me Kieffer <jerome.kieffer@terre-adelie.org>
