### ISSUE TITLE
Make a release for Python 3.10 support

### ISSUE THREAD

**Issue by JamesWrigley** [silx-kit/pyFAI#1607]
Hi there,
Python 3.10 was released last year, and there's a commit in `master` that fixes compatibility with it, #1588. Would it be possible to make a new release with this included? Another reason is for 3.10 wheels to be available on pip; otherwise the package needs to be built during installation, and that adds a couple of minutes to CI builds.

**Comment by kif** [comment]
I have planed a release of pyFAI in January and it will include wheels for 3.10. 
There are still some features to be polished and a foreseen compatibility issue with `numpy.distutils` used in `pyFAI` and `silx` which needs to be addressed before the release.
https://github.com/silx-kit/silx/pull/3581

**Comment by kif** [comment]
one step forwards: FabIO is released.

**Comment by GiuseppePortale** [comment]
Dear all,
I am trying to install pyFAI on my MACOS (Big Sur for now) with python 3.10 and I am having several issues.
One is with the wheels and another is with pyopencl.
Do I understand correctly that pyFAI is still not released for 3.10? What is the last version that is compatible? 3.9.0?
Thanks

**Comment by kif** [comment]
Hi Giuseppe,
The development version should be working ... at least it has been tested and everything tested is working on macos. 
https://gitlab.esrf.fr/silx/bob/pyfai/-/jobs/302410/artifacts/browse/artifacts/

About PyOpenCL, it is running on our mac-mini, that's all I can say. 
OpenCL on GPU is the way to go to get "good" performance on MacOS since their compiler is not OpenMP compliant.

Cheers,
Jerome

PS: MacOS is supported in best-effort mode.

**Comment by kif** [comment]
0.21 is out
