### ISSUE TITLE
Negative dimension exception in `AzimuthalIntegrator.integrate1d`

### ISSUE THREAD

**Issue by rayosborn** [silx-kit/pyFAI#1647]
When using `integrate1d`, I generate intermittent ValueError exceptions complaining of negative dimensions. This has proved impossible for me to diagnose because, when I run the code in a debugger, it completes successfully, but when I run it as a script from the command-line, it fails with the following traceback.
```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/test/bin/nxmax", line 33, in <module>
    sys.exit(load_entry_point('NXrefine', 'console_scripts', 'nxmax')())
  File "/home/rosborn/nxrefine/src/nxrefine/scripts/nxmax.py", line 47, in main
    reduce.nxmax()
  File "/home/rosborn/nxrefine/src/nxrefine/nxreduce.py", line 851, in nxmax
    self.write_maximum(maximum)
  File "/home/rosborn/nxrefine/src/nxrefine/nxreduce.py", line 928, in write_maximum
    self.calculate_radial_sums()
  File "/home/rosborn/nxrefine/src/nxrefine/nxreduce.py", line 950, in calculate_radial_sums
    polar_angle, intensity = ai.integrate1d(counts,
  File "/opt/anaconda3/envs/test/lib/python3.8/site-packages/pyFAI/azimuthalIntegrator.py", line 1252, in integrate1d_ng
    cython_integr = self.setup_CSR(shape, npt, mask,
  File "/opt/anaconda3/envs/test/lib/python3.8/site-packages/pyFAI/azimuthalIntegrator.py", line 564, in setup_CSR
    return splitBBoxCSR.HistoBBox1d(pos0, dpos0, pos1, dpos1,
  File "pyFAI/ext/splitBBoxCSR.pyx", line 109, in pyFAI.ext.splitBBoxCSR.HistoBBox1d.__init__
  File "pyFAI/ext/sparse_builder.pxi", line 870, in pyFAI.ext.sparse_builder.SparseBuilder.to_csr
ValueError: negative dimensions are not allowed
```
Here is the code that generates the issue:
```
from pyFAI.azimuthalIntegrator import AzimuthalIntegrator
ai = AzimuthalIntegrator(
                dist=parameters['Distance'],
                detector=parameters['Detector'],
                poni1=parameters['Poni1'],
                poni2=parameters['Poni2'],
                rot1=parameters['Rot1'],
                rot2=parameters['Rot2'],
                rot3=parameters['Rot3'],
                pixel1=parameters['PixelSize1'],
                pixel2=parameters['PixelSize2'],
                wavelength=parameters['Wavelength'])
print(counts.shape, pixel_mask.shape)
polar_angle, intensity = ai.integrate1d(
    counts, 2048,  unit='2th_deg',  mask=pixel_mask,  correctSolidAngle=True)
```
The parameters dictionary contains the scalar values derived from an earlier powder calibration using `GeometryRefinement`. The print statement confirms that the shape of the `counts` and `pixel_mask` NumPy arrays are both (1679, 1475) as expected for a Pilatus 2M detector, and certainly don't contain negative values.

This is with PyFAI v0.21.2 running in Python 3.8.12. This code used to work without problem, and, as I said, it still works in certain circumstances, such as when I am using a debugger. I have tried to test earlier versions of PyFAI, but these often produce other errors, such as a `MemoryError` and I can't find a configuration that doesn't produce the error.

Any suggestions about what other things I should check would be welcome.

**Comment by kif** [comment]
Hi Ray, thanks for the feed-back. 
It puzzles me that the bug is not reproducible ...

First of all, the bug appears in a section of code which was changed in version 0.21, early January, to have all integration engines using the same code and factorize all the cython code.

Since then, I got various bugs reported from the CI of debian on architectures like armel, i386, ... which are all 32-bit and do not perform floating point in strict ieee754. I tried to emulate those platforms (armel on armhf, i386 on amd64, ...) without being able to reproduce the bug and investigate it. Could you please provide me with the operating system of the computer, the CPU architecture, the number of cores and the amount of memory of the computer ? Can you try to run the test-suite of pyFAI ?
The `SparseBuilder`, written by @vallsv, is doing clever memory allocation and maybe there is a pitfall there. Valentin, could we meet to discuss about this issue ?

Ray, you did not provide any guidance to pyFAI about the engine to be used, and visibly it took `splitBBoxCSR` by default. There are several alternatives which can be selected with this extra argument to the call to integrate1d: `method=("bbox", "histogram", "cython")`. This should be a fail safe alternative producing the expected results. Replace "histogram" with "csr" to fall back on the buggy situation. If the problem is related to some memory constrains (which would explain the lack of reproducibility), you can try to use the  "csr" algorithm with another pixel splitting pattern having less contributions like "no" or "full" instead of "bbox" (this will slightly change shape of the integrated curve).

**Comment by rayosborn** [comment]
I have discovered that every combination of splitting and algorithm work fine when run within an IPython shell (including the `bbox` and `csr` options that caused the exceptions before). I am now checking to see what happens when I run them in a stand-alone script. I'm not sure why the other problems I mentioned in the last comment, i.e., with smearing and two-theta, don't show up in the shell, so please ignore them until I am able to reproduce it in other situations.

**Comment by rayosborn** [comment]
I had hoped to be able to provide a script, and files if necessary, that would allow you to reproduce this bug, but I cannot reproduce this behavior outside the workflow I am developing. I have written a stand-alone script that tests all the splitting and algorithm options, and they all work whether I invoke the script from the command-line or invoke the function within an IPython shell. I have tried increasing the memory footprint of the script, but that doesn't seem to make any difference. That probably means that you shouldn't spend any more time trying to diagnose this. 

The thing that baffles me is that, within the workflow, everything works if I choose `method=("no", "histogram", "cython")`, but if I switch to `bbox` splitting, things fall apart, i.e., I make no other changes in my workflow code except to the method argument that I pass to `integrate1d`. I either generate the 'negative dimensions' exception with `csr` or the returned values of `two_theta` are wrong and the integration is smeared out with `bbox`. 

Since the results with `method=("no", "histogram", "cython")` are acceptable to us, feel free to close this issue. Thanks for making the suggestion.

**Comment by kif** [comment]
Just a couple of comment, "no" pixel splitting is apparently better if one wants to perform Rietveld refinement according to Billinge:
https://arxiv.org/pdf/1309.3614.pdf
That said, most people prefer smoother curves.

About your computer/setup, it is very similar to the one we are using here. Unlikely that it comes from some CPU platform specificity.

The fact that `bbox` splitting gives crazy results (despite it is by far the best tested) puzzles me.
If you are able to reproduce the bug in any setup, could you please dump the content of the dictionary `ai._cached_array` to disk and send it to me, just to be sure if the bug is in the geometry calculation or in the regrouping part.

Cheers,

Jerome

**Comment by rayosborn** [comment]
I have sent a link to a pickle file containing `ai._cached_array`. Our Linux machine is running Fedora 35 with 104 cores and 24 x 32Gb = 768Gb memory modules.
```
$ uname -a
Linux nxrs0 5.15.13-200.fc35.x86_64 #1 SMP Wed Jan 5 16:39:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         46 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  104
  On-line CPU(s) list:   0-103
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Xeon(R) Platinum 8270 CPU @ 2.70GHz
    CPU family:          6
    Model:               85
    Thread(s) per core:  2
    Core(s) per socket:  26
    Socket(s):           2
    Stepping:            7
```

**Comment by kif** [comment]
I got the file, thanks, and it confirms that the bug in `dtth` i.e. the distance in 2theta from the pixel center to the corner.
This explains not only why all `bbox` pixel splitting are giving crazy results but also why the bug is so difficult to reproduce. The `dtth` array got corrupted, maybe some cache invalidation not working properly, maybe something overwrote the numpy array in the cache.

I had a look at the other arrays:

* The 2theta array looks OK, with a beam-center almost in a corner and angles going up to 27° (those angles are supposed to be stored in radians). Can you confirm this corresponds to your experimental setup ?
* The delta-2theta array is completely corrupted with values which are very large, maybe a conversion rad2deg ? 
* The array containing the coordinates of the pixel corners in polar space is also corrupted, which explains why the delta-2theta is corrupted. 
* all other arrays looks OK.

Any value in `numpy.max(ai._cached_array.get('2th_corner', 0))` greater than 2pi indicates a cache corruption. Maybe this will help you spot where this corruption occured.
Nota, there is an `ai.reset()` method which cleans the cache an resets all integration engines. Useful to enforce the re-initialization without re-creating the `ai` object.

**Comment by rayosborn** [comment]
Here is an image of one of our powder calibrations. As you saw, the centre is in the bottom-right corner, with an incident wavelength of 0.142Å and a detector distance of ~640mm giving a maximum 2theta of ~27°.
<img width="476" alt="sector6" src="https://user-images.githubusercontent.com/1193959/155572409-d4fb515c-77ab-489c-96bd-598b58a12cf6.png">
We don't provide either a 2theta or delta-2theta array. I presume that is generated from the PONI parameters. You can see how we create the `AzimuthalIntegrator` instance and then invoke `integrate1d` in my original post, but the code was slightly simplified. For example, we correct the counts for the beam polarization before calling `integrate1d`. This is the actual code:
```
            ai = AzimuthalIntegrator(
                dist=parameters['Distance'].nxvalue,
                detector=parameters['Detector'].nxvalue,
                poni1=parameters['Poni1'].nxvalue,
                poni2=parameters['Poni2'].nxvalue,
                rot1=parameters['Rot1'].nxvalue,
                rot2=parameters['Rot2'].nxvalue,
                rot3=parameters['Rot3'].nxvalue,
                pixel1=parameters['PixelSize1'].nxvalue,
                pixel2=parameters['PixelSize2'].nxvalue,
                wavelength=parameters['Wavelength'].nxvalue)
            polarization = ai.polarization(factor=0.99)
            counts = (self.summed_data.nxvalue.filled(fill_value=0)
                      / polarization)
            polar_angle, intensity = ai.integrate1d(
                counts, 2048, unit='2th_deg', mask=self.pixel_mask,
                correctSolidAngle=True, method=('bbox', 'csr', 'cython'))
```
The `nxvalue` attribute just converts NeXus fields into scalar values. The counts are originally stored as a NumPy masked array, but is converted to a regular NumPy array when we apply the polarization correction. The mask values are then stored in `self.pixel_mask`. It is possible that the counts array contains spurious values, although I don't think there are any NaNs. Those values should be masked by `self.pixel_mask` in any case.

**Comment by rayosborn** [comment]
I tried `ai.reset()` before calling `ai.integrate1d` but it makes no difference. Apart from the call to `ai.polarization`, the instance is not modified after creation. 

I modified the code to print out the value of `np.max(ai._cached_array.get('2th_corner', 0))` after creating `ai`, calling `ai.polarization`, after an `ai.reset`, and after calling `ai.integrate1d` and the value was always 0, except when the call to `integrate1d` triggers the exception, when it is 326.6565. If I revert to `method=('no', 'histogram', 'cython')`, it is still 0 after the call to `integrate1d`.

**Comment by kif** [comment]
I tried this:
```
import pyFAI, numpy
ai = pyFAI.AzimuthalIntegrator(0.640, detector="Pilatus2m", wavelength=0.142e-10)
polarization = ai.polarization(factor=0.99)
msk = ai.detector.mask
res1 = ai.integrate1d(polarization, 2048, unit='2th_deg', mask=msk, correctSolidAngle=True, method=('bbox', 'csr', 'cython'))
numpy.max(ai._cached_array.get('2th_corner', 0))
```
and this all works event as expected.
But if I initialize the azimuthal integrator like you do, I get an exception because the detector shape is not known:
```
ai = pyFAI.AzimuthalIntegrator(0.640, pixel1=172e-6, pixel2=172e-6, wavelength=0.142e-10)
polarization = ai.polarization(factor=0.99)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-25-adb9df239db6> in <module>
----> 1 polarization = ai.polarization(factor=0.99)

/usr/lib/python3/dist-packages/pyFAI/geometry.py in polarization(self, shape, factor, axis_offset, with_checksum)
   1836         shape = self.get_shape(shape)
   1837         if shape is None:
-> 1838             raise RuntimeError(("You should provide a shape if the"
   1839                                 " geometry is not yet initiallized"))
   1840         if factor is None:

RuntimeError: You should provide a shape if the geometry is not yet initiallized
```
How did you initialize your detector ? 
What is `ai.detector.shape` in your case, does it match the Pilatus2M ? Maybe some unexpected broadcast.
I suspect the content of the cache did fool the `guess_shape` method defined:
https://github.com/silx-kit/pyFAI/blob/master/pyFAI/geometry.py#L2150

But when I look at the content of the cache you sent me, it all looks OK:
```
In [8]: for k,ary in cache.items():
   ...:     if ary is not None:
   ...:         if hasattr(ary, "shape"):
   ...:             print(k, ary.shape[:2])
   ...:         elif hasattr(ary, "array"):
   ...:             print(k, ary.array.shape[:2])
   ...: 
   ...: 
2th_center (1679, 1475)
chi_center (1679, 1475)
PolarizationDescription(polarization_factor=0.99, axis_offset=0.0) (1679, 1475)
last_polarization (1679, 1475)
cos_incidence (1679, 1475)
solid_angle#3.0 (1679, 1475)
2th_corner (1679, 1475)
2th_delta (1679, 1475)

In [9]: pyFAI.detector_factory("pilatus2M").shape
Out[9]: (1679, 1475)
```

**Comment by rayosborn** [comment]
It derives the shape from the PONI detector parameter, which is set to 'Pilatus CdTe 2M'. In the debugger, `ai.detector.shape` is correctly set to (1679, 1475) after initializing the `AzimuthalIntegrator`. Ironically, I used to explicitly define the shape in the call to `integrate1d`, but I removed it when I encountered the negative dimension error and realized that the `ai` instance stored the shape anyway. I thought that perhaps my code was getting the shape wrong.

**Comment by kif** [comment]
I have one doubt : can you print the azimuthal integrator ? Is the detector actually a Pilatus or is it a Nexus-detecor ? If a file exist with the same name as the detector and contains a detector definition, this could lead to loading the pixel coordinates from that files. Unlikely but not impossible.

The function to generate the corner array is ` ai.corner_array(unit="2th_rad")`. Can you check the result obtained looks OK ? at least that there are no values outside the range -pi/pi ? This function can `use_cython` or not and the results should be the same (within the numerical precision which is around 1e-7). Mind to reset the integrator between calls since the result is cached.
