### ISSUE TITLE
`extract_cp` with default parameters gives me poor results for ED

### ISSUE THREAD

**Issue by elena-pascal** [silx-kit/pyFAI#1677]
Hello pyFAI team, 

I have a question. I am looking at calibrating some ED powder patterns with pyFAI. I want to do this using the python API. This is how typical "good" calibration data looks like (this is polycrystaline Al, I showed this data here before).

![Yuns_eBIC Al_powder](https://user-images.githubusercontent.com/30300213/163979768-e5aeae71-6ed6-4d20-94b9-37998d9871b2.png)

I broadly followed [this tutorial](https://pyfai.readthedocs.io/en/master/usage/tutorial/Recalib/Recalib_notebook.html) and in general it does improve geometry. But I think the data I work with has a) more sparse spots per rings and b) somewhat more dense rings.

My question has to do with how to drive peak picker with `SingleGeometry.geometry_refine`? I did use the `Imin` in `starting_geom.extract_cp()` but that only helps so much especially since spots intensities fall rapidly at higher resolutions so if I set it too high I risk having no spots picked at higher ring numbers. If the starting geometry is less than perfect, the peak picker gives me poor results. What I am looking for is a Gaussian parameter to control the expected peak shape and perhaps the distance from the calibrant rings allowed. I know these are set at lower levels but I can't figure out how to control them from the `extract_cp` layer.

![peakpicker](https://user-images.githubusercontent.com/30300213/163976461-b0235450-1d34-4563-b07a-6add72969c91.png)

Thank you for your work

**Comment by kif** [comment]
Dear Elena,

I have been working recently on the integration of the calibration widget into jupyter (notebook and lab) and it allows to manually pick some control points. This should allow you to bootstrap a "reasonnable" geometry and get automatic peak-picking doing their job properly.
Since this is a recent addition, there is no release with it (yet) but could you please give a try at this tutorial:
https://github.com/silx-kit/pyFAI/blob/master/doc/source/usage/cookbook/calibration_with_jupyter.ipynb
after having installed the current master version.

To answer your question, the single-geometry has been recycled from the goniometer calibration (thus its name) and contains  not only a geometry-refinement part but also a peak-picker part which can use 3 algorithms called "massif", "blob" and  the last collects all pixels. It is likely the later was used.
Massif is probably the best suited but requires a gaussian_width parameter. Play with this parameter the default guess depends on  the size of the image ... but 20 should be OK. Important: mask out invalid area since massif is easily fooled.

Cheers,

Jerome

**Comment by elena-pascal** [comment]
Dear Jerome, 

Thank you for getting back to me and for integrating the calibration widget into jupyter, it is great fun to use, I'm looking forward to wrapping it for our project. 

I had previously written a widget which would allow the user to move the calibration rings over the image in order to obtain a reasonable starting geometry for these cases when rings are too dense to let refine run wild. I think I prefer the manual control point picking, it's more effective and less clunky than my solution.

I do understand your point, if the starting geometry is very close, which the manual control point picker is good at achieving, then the peak picking in the refinement step will indeed produce expected results even for much worse looking data than what I showed here. 

I will keep thinking about the peak picking behavior for less than ideal data with somewhat off staring geometries, but I am happy to close the question for now since that can be circumvented with available tools discussed here.

Thank you, 
Elena
