### ISSUE TITLE
worker does not allow for azimuthal error model

### ISSUE THREAD

**Issue by woutdenolf** [silx-kit/pyFAI#1701]
No matter what I try, the worker does not seem to accept error models otther than poisson

```python
from pyFAI.worker import Worker

worker = Worker(extra_options={"error_model", "azimuthal"})
worker.do_azimuthal_error = True
worker.set_config({"error_model", "azimuthal", "do_azimuthal_error":True})
worker.error_model = "azimuthal"
```

**Comment by kif** [comment]
Indeed, because this is the only one available for azimuthal integration...
If you wish to use an azimuthal error model, you have to go via sigma-clipping with zero clipping cycles (at least for now).
Moreover the sigma-clipping is not yet implemented in all drivers, sometimes it is not easy (python) and I did not test the equivalence of those implementation.
