### ISSUE TITLE
'JupyCalibWidget' object has no attribute 'widget'

### ISSUE THREAD

**Issue by emathew16** [silx-kit/pyFAI#1785]
I am very new with .edf files and was trying to redo the example given on the website. Can someone help me with this? I tried to downgrade the version too but the error still remained.
![error](https://user-images.githubusercontent.com/88091762/207631913-5baf0e59-1885-4480-b058-a44482e52f83.png)

**Comment by kif** [comment]
I checked the tutorial (with pyFAI 0.21.3) and it does works for me ... If you are new to pyFAI, I would recommend you to start with pyFAI-calib2. It is a fully integrated GUI (running in Qt). 
http://www.silx.org/doc/pyFAI/latest/usage/cookbook/calib-gui/index.html

The tutorial you are following requires to be familiar with the jupyter environment.
Could you detail your installation: Apparently you are running pyton3.8 installed with Conda. Could you precise if you are running the tutorial from `jupyter-notebook` or `jupyter-lab` (since there is a difference in the initialization of matplotlib).
Could you provide the version of pyFAI, jupyter, matplotlib, ipympl, and also the URL from where you downloaded the notebook: Those notebook are validated and adapted for each release (both to adapt to new features in pyFAI and also because the notebook environment evolves)

As a rule of thumb I would rather upgrade than downgrade. The version number provided in the notebook are the minimum guaranteed.

**Comment by emathew16** [comment]
The tutorial is from: http://www.silx.org/doc/pyFAI/latest/usage/cookbook/calibration_with_jupyter.html
![details](https://user-images.githubusercontent.com/88091762/207671534-d9de6368-5a56-4723-9250-70a55ad2ebcf.png)

**Comment by emathew16** [comment]
It is working now. I just installed ipympl. I installed all the dependencies using pip install -r requirements.txt, Thank you so much for ur reply. Sorry for the trouble. I am also checking pyFAI-calib2. I always preferred jupyter notebook.

**Comment by kif** [comment]
No problem, thanks for pointing the issue, I will update the tutorial to highlight that `ipympl` is needed for this specific tutorial (it is not a general requirement for pyFAI).
