### ISSUE TITLE
Support sigma-clipping with pixel splitting

### ISSUE THREAD

**Issue by woutdenolf** [silx-kit/pyFAI#1825]
As far as I understand the current `sigma_clip_ng` implementation does the clipping before the splitting. If you want both it should be the other way around. `sigma_clip` does in the other way around but it is not supported by the `Worker` class. It also gives a deprecation warning.

**Comment by kif** [comment]
Hi Wout,
I believe this is a documentation issue ... Despite `sigma_clip` and `sigma_clip_ng` provide the same kind of result, i.e. a smooth scatting curve after having removed the contribution from Bragg peaks originating from larger single crystals.

*   `sigma_clip` operates as described in https://doi.org/10.1017/S0885715613000924 (Figure 2) except the median filter has been replaced by a a sigma-clipping on the 2D regrouped data. This initial 2D regrouping should optimally be performed with pixel-splitting to provide the smoothest curve, even close to the beam-stop.
*  `sigma_clip_ng` has not yet been published but it fully operates in the detector space using solely a sparse representation of the transformation. Using pixel splitting degrades the quality of the uncertainties provided (as demonstrated in the **variance** tutorial). The largest problem is likely pixels which are split into several bins, and are found to be inlier in some of them and outlier in others. 

Your suggestion is to use a CSR matrix without pixel splitting in first instance to dynamically mask-out Bragg-peaks and finally use a different CSR matrix (with pixel splitting) to produce the result ? Those CSR matrices are pretty large, I am not sure having several of them in memory is a good idea.

Last comment: There used to be bugs in the weight of the pixel when using the azimuthal error models together with pixel splitting but I believe this is fixed in the latest release (I spent most of year 2022 on this specific topic)

**Comment by woutdenolf** [comment]
I propose the keep `sigma_clip` to support sigma-clipping with pixel splitting:

* remove the deprecation warning
* support it by the worker class (or perhaps make a new method based in integrate + post-clipping with an API that is compatible with the worker)

**Comment by kif** [comment]
I opened a PR which exposes it into the documentation. 
https://github.com/silx-kit/pyFAI/pull/1828
The deprecation warning is a consequence of `integrate2d_legacy` being deprecated ...

**Comment by woutdenolf** [comment]
Do you think it is possible to support in the `Worker` class?

**Comment by kif** [comment]
I will have a look (probably not today)

**Comment by kif** [comment]
By now, the documentation should have been updated, re-integrating the legacy version.

Apparently `sigma_clip_ng` works but not the legacy version ... Is this the kind of bugs you observed ?
```
In [1]: import pyFAI; from pyFAI.worker import Worker

In [2]: ai = pyFAI.load({"detector":"Pilatus1M", "wavelength":1e-10})

In [8]: w = Worker(ai, ai.detector.shape, (1,1000), integrator_name="sigma_clip_ng")

In [11]: w(img)
Out[11]: 
array([[1.23139582e-01, 0.00000000e+00, 4.78955511e+17],
       [3.69418747e-01, 0.00000000e+00, 4.57061520e-41],
       [6.15697912e-01, 0.00000000e+00, 4.78955511e+17],
       ...,
       [2.45663467e+02, 0.00000000e+00, 0.00000000e+00],
       [2.45909746e+02, 0.00000000e+00, 1.02594383e-36],
       [2.46156025e+02, 3.17539871e-01, 0.00000000e+00]])

In [12]: w = Worker(ai, ai.detector.shape, (1,1000), integrator_name="_sigma_clip_legacy")

In [13]: w(img)
ERROR:pyFAI.worker:error in integration do_2d: False
TypeError
_sigma_clip_legacy() got an unexpected keyword argument 'safe'
data.shape: (1043, 981)
data.size: 1023183
ai:
Detector Pilatus 1M	 PixelSize= 1.720e-04, 1.720e-04 m
Wavelength= 1.000000e-10 m
SampleDetDist= 1.000000e+00 m	PONI= 0.000000e+00, 0.000000e+00 m	rot1=0.000000  rot2=0.000000  rot3=0.000000 rad
DirectBeamDist= 1000.000 mm	Center: x=0.000, y=0.000 pix	Tilt= 0.000° tiltPlanRotation= 0.000° 𝛌= 1.000Å
method:
IntegrationMethod(1d int, bbox split, CSR, cython)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-c8d42c314bcb> in <module>
----> 1 w(img)

/usr/lib/python3/dist-packages/pyFAI/worker.py in process(self, data, variance, normalization_factor, writer, metadata)
    401                     ]
    402             logger.error("\n".join(err2))
--> 403             raise err
    404 
    405         if writer is not None:

/usr/lib/python3/dist-packages/pyFAI/worker.py in process(self, data, variance, normalization_factor, writer, metadata)
    376         error = None
    377         try:
--> 378             integrated_result = self._processor(**kwarg)
    379             if self.do_2D():
    380                 self.radial = integrated_result.radial

TypeError: _sigma_clip_legacy() got an unexpected keyword argument 'safe'
```

**Comment by woutdenolf** [comment]
Yes indeed, the legacy version is not supported by the worker class. I get the same exception. `sigma_clip_ng` works fine.
