### ISSUE TITLE
Does integrate1d normalize the intensity with SDD?

### ISSUE THREAD

**Issue by OkKakao** [silx-kit/pyFAI#1966]
Hi

I'm currently using pyFAI to analyze the scattering image.

I'm trying to calculate the conversion factor between the detectors, but it is not sure whether the integrated array is normalized by SDD (sample to detector distance) or not.

Does the function integrate1d normalizes the intensity with SDD which is contained in the PONI file?

Thank you

**Comment by kif** [comment]
By default, the solid angle of each pixel is taken into account. It can be disabled when calling the method `integrate[12]1d`.

The pixel at the PONI has no correction in intensity (i.e. a correction of 1) while all other see their intensity increase because they have a smaller solid angle. In SAXS, this does not matter but in WAXS/powder/PDF this can be huge, in the order of 50x.
If you wish to have your intensity per stradian, you have to multiply the output of the integration dist²/(pixel1*pixel2) (this is a **constant**, same value for all pixels, since the relative correction has already been applied).

In pyFAI, it is done via normalization, thus the invert of what is written just above and it is implemented here:
https://github.com/silx-kit/pyFAI/blob/main/pyFAI/geometry/core.py#L1278

Absolute solid angle correction is only used when doing multi-geometry integration.

**Comment by OkKakao** [comment]
Thank you for your help!
I should think more about what is real problem...
