### ISSUE TITLE
Poni file generated by Dioptas are incompatible with pyFAI ?

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#1994]
Apparently the images are flipped somewhere.

Spotted at ID27
Thanks @t20100 @loichuder @EdgarGF93
attn @CPrescher

**Comment by kif** [comment]
We should organize a meeting to discuss the different options possible

**Comment by CPrescher** [comment]
This has been the case since ten years. In order to be able to convince previous fit2d users, I decided to follow the image orientation in fit2d. Which basically means the origin is on the lower left system. To be able to use a poni file from pyfai in dioptas or vice versa the image just has to be flipped vertically.

**Comment by CPrescher** [comment]
This has been the case since ten years. In order to be able to convince previous fit2d users, I decided to follow the image orientation in fit2d. Which basically means the origin is on the lower left system. To be able to use a poni file from pyfai in dioptas or vice versa the image just has to be flipped vertically.

**Comment by CPrescher** [comment]
One thing which actually would be great also for other use cases, if the poni file could also save image transformations Like rotations or flips

**Comment by bwehinger** [comment]
Maybe smarter would be if poni files are always generated for non-flipped images. If some programs like Dioptas want to apply image transformations than they should transform the geometry of the poni file. 
@kif Do you know how to transform the geometry and how to convert a poni file such that it works on transformed images?

**Comment by kif** [comment]
This works only with Fit2d if users were using TIFF files, it did not work with EDF...

Beside this, maybe one could consider adding a orientation tag into the detector definition.... possible, not simple

**Comment by kif** [comment]
Hi Bjorn,
The flipping of the image changes the sign of the azimuthal angle thus not possible to convert the PONI file.

**Comment by kif** [comment]
We could define a detector orientation tag, and get inspired by:
http://sylvana.net/jpegcrop/exif_orientation.html

* [ ] create the detector orientation tag: value 0 to be used for "do not care" else value [1..8]
* [ ] Use this tag when calculating the pixel center coordinate
* [ ] Use this tag when calculating the pixel corner coordinate
* [ ] Use this tag when calculating the x,y,z of a list of pixels (used while calibrating)
* [ ] Save / restore this attribute into the Nexus detector file
* [ ] Save / restore into the PONI-file
* [ ] Save / restore into the config
* [ ] Ensure the Detector cache gets reset when changing the orientation (--> use a property)
* [ ] Ensure the geometry cache gets reset when changing the orientation ( what is the best way of doing this ?)

**Comment by EdgarGF93** [comment]
I think many users and scientist do not think about the rotation issue and rot3 value when they are using pyFAI-calib, because it's not obvious to spot and if even you know how your detector is mounted or if there is some kind of flipping, it's easy to forget between experiments.
So, I think it could be good to use this detector tag, as long as the user is aware of it at some point during the pyFAI-calib protocol. For example, an explicit visualization of the origin and the (+) axis over the detector image.

**Comment by kif** [comment]
In pyFAI-calib2, there are visualization options to redisplay the image in 2D or 3D (requires OpenGL unfortunately, pretty slow)

**Comment by EdgarGF93** [comment]
One possibility could be allowing the user to change the flipping right from the first step of pyFAI-calib2 (and that would change rot3). The same way you are reading the characteristics of your detector array, you would have here a label of its orientation.
![Screenshot from 2023-11-15 13-41-34](https://github.com/silx-kit/pyFAI/assets/112327909/e61486ce-bb1a-4998-a51b-8ee4380174c2)

**Comment by kif** [comment]
I am not sure this is a priority ... the best is that the user does not fiddle with this parameter since it is likely to jeopardize the subsequent analysis.

**Comment by bwehinger** [comment]
It would be great to make PONI files compatible and the detector orientation flags are indeed a good idea to do so. 
@kif Thanks for this suggestion

**Comment by kif** [comment]
Don't get excited too quickly since:
* it will require a couple of months to get it implemented, tested and validated
* it will require a new release of pyFAI
* Then  Dioptas needs to take care of this additional parameter
* and Dioptas needs a new release.

**Comment by loichuder** [comment]
Regardless of the time it will take, I think it is an elegant way of solving the issue at hand !

Don't be such a wet blanket @kif  :joy:

**Comment by CPrescher** [comment]
Having an extra orientation tag is great, and I will gladly include it in dioptas. This is specifically important for the difficult detector setups at XFELs since most of the time detectors are rotated and flipped based on space availlable. Often multiple detectors are used and it is hard to keep track of this. Having this saved in the poni file will help this use-case greatly and reduce the headaches these setups can create.
