### ISSUE TITLE
`extract_cp` loop runs for all calibrant 2 theta values

### ISSUE THREAD

**Issue by emilymassahud** [silx-kit/pyFAI#2078]
Hey, I am working on a ring extraction routine at the Australian Synchrotron, and using `SingleGeometry.extract_cp` as a guide. I was trying to speed up the execution time and noticed that the loop for peak extraction in each ring runs many times more than it needed to, because if no `max_rings` is given, it goes over all the dspacings for that given calibrant (https://github.com/silx-kit/pyFAI/blob/main/src/pyFAI/goniometer.py#L681). 
I came out with a simple solution to calculate `tth` as only the calibrant two theta values which are smaller than the maximum value in `geometry_refinement.twoThetaArray`, to decrease unnecessary overhead.

Some other changes I made were:
- I was able to make a `RingExtraction` class from all I gathered from `extract_cp`, breaking it down to smaller tasks and facilitating unit testing;
- I used `ThreadPoolExecutor` from `concurrent.futures` to run ring extraction on multiple rings at a time, reducing execution time from 15s to 6s in my local dev machine.

**Comment by kif** [comment]
Hi Emily,
Thanks for you interest in pyFAI. I have to admit this piece of code has been written for readability more than performances (in the scope of this publication https://doi.org/10.1107/S1600577520000776 ), so you points are perfectly valid...   
When reading the code, I find several places where optimisation could be made (several arrays are re-calculated at each loop, using the `out=` parameter for mask would also save several malloc, ...). 

When it comes to threads, it would probably be better to optimize the outer-most loop, i.e. the extraction of the control-point per image rather than the extraction of the rings in each image. Both would be valuable, so there should be a mechanism to disable the thread-pool mechanism as it is done in https://github.com/silx-kit/pyFAI/blob/main/src/pyFAI/multi_geometry.py#L164
Using a class instance is probably needed to manage the thread-pool, proper deletion & garbage collection has to be kept in mind to avoid memory leaks.

Can you propose a PR or share your code  ?

**Comment by kif** [comment]
I did some line-profiling: 
In `SingleGeometry.extract_cp`  ~70% of the time is spent in `massif.peaks_from_area()` method.
In `Massif.peaks_from_area`, ~70% of the time is spent in `pyFAI.utils.is_far_from_group` which is implemented as a python loop ...

**Comment by kif** [comment]
About the loop on all reflections of the calibrant, it is easily "vectorisable":
With one loop on all pixels of the detector one can create a `qmask` array: each pixel contains the value of the ring number to which it is affected. With this loop written in cython, the number of pixels associated to each reflection can also be counted which makes the loop over all reflections much faster (unless all reflections are to be probed).

Concerning the `pyFAI.utils.is_far_from_group` function, I re-implemented it in numpy and it is much slower (~8x when probing 10 points). I could implement it in cython but with the GIL. The speed-up would likely be only 30-50%
