### ISSUE TITLE
Slow for numerous AI creation.

### ISSUE THREAD

**Issue by Saldenisov** [silx-kit/pyFAI#2100]
The problem goes like this:

We have ~2000 measurements (256*256 pixels) that are basically all measured at slightly different distances. 

Thus, in order to integrate images, we need to create many AI instances. 

Is there another way to increase the speed of integration than doing cached AI?

```
@lru_cache(maxsize=None)
def initialize_azimuthal_integrator(
    pixel_size, center_column, center_row, wavelength_A, sample_distance_mm
):
    detector = Detector(pixel_size, pixel_size)
    ai = AzimuthalIntegrator(detector=detector)
    ai.setFit2D(
        sample_distance_mm, center_column, center_row, wavelength=wavelength_A
    )
    return ai
```

I tried creating one AI and then calling `setFit2D` function for the new distance measurement. But I do not know if it correct.

thanks

**Comment by kif** [comment]
How slow is slow ? In multigeometry, we are creating hundreds of `ai` instances without noticeable issue.  can you provide figures.

The lru_cache is likely to fill up the memory, did you check ?

Beside this, if the detector is always the same, it should be the same object.
Since your detector is untilted, you can convert the sample_distance_mm, center_column, center_row and call directly the constructor of Azimuthal integrator:
```
ai = AzimuthalIntegrator(sample_distance_mm*1e-3,
                                             center_row*pixel,
                                             center_column*pixel,
                                             detector=detector,
                                             wavelength=wavelength_A*1e-10)
```

**Comment by kif** [comment]
For 1000 geometries to be created, timing measured using `%timeit` in a notebook:
* `[pyFAI.load({"dist":d, "poni1":p1, "poni2":p2, "detector":detector})for d,p1,p2 in zip(dist_m, poni1, poni2)]` : 37.6s
* `[AzimuthalIntegrator(d, p1, p2, detector=detector) for d,p1,p2 in zip(dist_m, poni1, poni2)]`: 5.63ms
* `[initialize_azimuthal_integrator(pixel_size, c, r, wavelength_A, d) for d,c,r in zip(sample_distance_mm, center_column, center_row)]`: 147s
* `[initialize_azimuthal_integrator_uncached(pixel_size, c, r, wavelength_A, d) for d,c,r in zip(sample_distance_mm, center_column, center_row)]`: 147s

Conclusion: by using directly the constructor of the class, it is 26000x faster :smile:
The reason is mostly because one creates a geometry, then changes it which locks, reset the geometry then unlocks it.

**Comment by kif** [comment]
Note the usage of lru_cache does not help with the speed.
