### ISSUE TITLE
Performance issue in debian9 on OpenCL

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#670]
Benchmarks have seen the performances of OpenCL integration divided by ~10 with the migration from Debian8 -> Debian9.
The good point is that integration is now independant of the image size :/

**Comment by kif** [comment]
I confirmed the behaviour by bisecting the releases of pyopencl. It is due to the migration from Boost -> CFFI

**Comment by kif** [comment]
A quick profiling of integrate1d indicates a lot of time is spent in "compile" at the CFFI level for every call.

**Comment by kif** [comment]
Andreas (@inducer) suggested the solution:

The one reason I can imagine you might see a slowdown like that is
if you do not save your kernels, i.e. do

prg.mykernel(...)

instead of

knl = prg.mykernel # ideally once in the whole program
knl(...)

The first way used to be cheap, but it no longer is. In order to improve
invocation cost, PyOpenCL now just-in-time-generates some Python to help
call the kernel. That generation process is fairly expensive, and the
result is cached in the kernel--so if you keep throwing away the
kernels, you keep incurring that generation cost.

If that's not it, then a reproducer would be fantastic.

Best,
Andreas

**Comment by picca** [comment]
Hello Jerome, what about  an API which use __enter__ __leave in order to do this costly pre-computation only once.

with Integrator... as ai:
     use the integrator.

but in the use integrator it is not allowed to use parameter which require to regenerate csl, lut etc...

**Comment by kif** [comment]
Hi Fred,

The compilation of the kernel was in the order 5 ms, it is huge compared to the normal integration time with a high-end GPU (1ms), but very small compared to the seconds it takes to generate the sparse matrix used during the integration.
Azimuthal Integrator objects have now a "reset" methods that cleans up all regriding engines associated: OpenCL or Cython and frees all the memory. This will be part of 0.14.2 as well

We have a patch in PR which fixes actually the regression.

**Comment by picca** [comment]
Hello, Jerome, what I understand from this is that you avoid a memory leak by adding a reset.
Or this is to expresse the fact that one operation take a lot's of time. the sparse matrix computation.
In that case reset seems to me not really explicite ;)

How do we explain to the user what cost a lot and what is efficient ? in the API.
Now it seems to me that during the integration1D or 2D the recomputation of the costly sparse matrix
can happend.

This cause some trouble because peoples do not understand why pyFAI is slow.

```python
with Integrator(Detector, Image shape, Mask, Flat, Poni) as ai:
    res = ai.integrate1D(img)
```

We can even imagine something more generic

```python
 with Integrator1D(f) as ai:
    res = ai.run(img)
```

where

the `f` function is something generic f(...) which return a transformation from 2D to an histogram1D
or Histogram2D for an integrator2D.

nevertheless all this could de discuss for a pyFAI 2.0 ;)
