### ISSUE TITLE
Segfault on python3 rnice9

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#778]
```
valls@rnice9-0308:~$ ipython3
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import pyFAI

In [2]: pyFAI.version
Out[2]: '0.15.0'

In [3]: pyFAI.tests()
Segmentation fault

```

**Comment by vallsv** [comment]
It looks to be fine on rnice8 (python 2 and 3) and rnice9 with python2

**Comment by kif** [comment]
On Fri, 02 Feb 2018 06:27:13 -0800
Valentin Valls <notifications@github.com> wrote:

> ```
> valls@rnice9-0308:~$ ipython3
> Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
> Type "copyright", "credits" or "license" for more information.
> 
> IPython 5.1.0 -- An enhanced Interactive Python.
> ?         -> Introduction and overview of IPython's features.
> %quickref -> Quick reference.
> help      -> Python's own help system.
> object?   -> Details about 'object', use 'object??' for extra details.
> 
> In [1]: import pyFAI
> 
> In [2]: pyFAI.version
> Out[2]: '0.15.0'
> 
> In [3]: pyFAI.tests()
> Segmentation fault
> 
> ```

OK on scisoft14
OK on scisoft13

The bug is related to OpenCL 
I guess this is because only pocl 0.13 is intalled.
I packaged AMD and intel icd's on scisoft13 and 14 which explains why it works.
So this bug is similar to the on reported by Fred on Debian-CI.
I should get in contact with POCL team to fix their compiler.

**Comment by vallsv** [comment]
It's fine then. Thanks a lot for  checking.
