### ISSUE TITLE
integrate1d: binning in log space

### ISSUE THREAD

**Issue by Miradin** [silx-kit/pyFAI#820]
As output parameter of integrate1d we are obtaining scattering vector linearly spaced. Is it possible to obtain scattering vector values log spaced instead of linear? Such an option would be very useful for SAXS data, because Log-Log graphs are quite often used.
Would be great to make an additional option for "radial_range".
With pixel splitting algorithm, it should be more accurate than just to use interpolation function from numpy or scipy.

**Comment by kif** [comment]
Hi Miradin,

I believe this options is already available (while I have not been convinced as log-scale distorts considerably the scale). 

Warring !!
Any mathematical transformation creating negative values in radial data is likely to give wrong results with  some integrators (which do not accept negative radius).

You must specify the options for the output unit when calling integrate1d or integrate2d of your azimuthal integrator. If you use a GUI, it is likely this option is not exposed in the interface.
 
Here is a list of all radial units registered in the latest version of pyFAI.
* 2th_deg,
* 2th_rad,
* arcsinh(q.A)_None,
* arcsinh(q.nm)_None,
* d*2_A^-2,
* d*2_nm^-2,
* log(1+q.A)_None,
* log(1+q.nm)_None,
* log(q.nm)_None,
* log10(q.m)_None,
* q_A^-1,
* q_nm^-1,
* r_m,
* r_mm

The actual unit is represented after the underscore. Have a look at arcsinh(q.nm)_None and log(1+q.nm)_None if they fit your needs.

Cheers,

Jerome

**Comment by kif** [comment]
Hi Alexander,
There is a new version of pyFAI (0.15.0). I don't think it impacts what we are discussing about but I advice you to upgrade.

Concerning the *warning*, this is completely normal. I added a way to define your own units very simply.
Have a look at pyFAI.units where we define all our units:
```
register_radial_unit("arcsinh(q.nm)_None",
                     scale=1.0,
                     label=r"arcsinh($q$.nm)",
                     equation=lambda x, y, z, wavelength: numpy.arcsinh(eq_q(x, y, z, wavelength))) 
```
The warning is because this equation is provided in python/numpy and hence not optimized using some OpenMP (like 2theta or q). The numerical values are correct, just not as fast for the initialization.

The problem of bin spacing you have noticed is related to the constantly changing curvature of log-like function. Integrating with unit="arcsinh(q.A)_None" should already help as there is a factor 10 between nm and A. If this is not yet enough, I invite you to define your own unit.

I will add a cookbook example on this issue in the doc
![Uploading Figure 7.png…]()


Cheers,

Jerome

**Comment by Miradin** [comment]
Hello, Jerome.
I have upgraded to 15.0 version now. Reading through register_radial_unit function has clarified some aspects. I will play with that.
Please, take a look on this strange results. 
Using units "q_A^-1" and "arcsinh(q.A)_None" is the only difference.

This is the code I use:

```Python
r_range = (0.01, 0.5)
a_range = (0, 360)
q, I, sigma = ai_long.integrate1d(data, 50, error_model="poisson", radial_range=r_range, azimuth_range=a_range, mask=maskdata, method="BBox", unit="arcsinh(q.A)_None")
q = np.sinh(q) #should I do that as obtained scale was in arcsinh(A) values?
plt.loglog(q, I, '+')
q, I, sigma = ai_long.integrate1d(data, 50, error_model="poisson", radial_range=r_range, azimuth_range=a_range, mask=maskdata, method="BBox", unit="q_A^-1")
plt.loglog(q, I, 'o')
```
result... notice intensity change and decreased q-range:

![intensity_scaling](https://user-images.githubusercontent.com/37274960/38673134-ad4f29de-3e50-11e8-8357-a6593137f1f1.png)

Use same code but with r_range=None (for full range according to description in azimuthalIntegrator.py) The result becomes more strange: 
![q_scale_shift](https://user-images.githubusercontent.com/37274960/38673489-c6e53bf8-3e51-11e8-9f24-188042025b2d.png)


Best regards,
Alexander

**Comment by Miradin** [comment]
Just to make it clear, this is the effect I want to obtain (result produced on same data with same range, using same amount of points[50]):
![matlab_lin_log_correct](https://user-images.githubusercontent.com/37274960/38674501-f12aefe0-3e54-11e8-90bd-2c312bb4d22c.png)

**Comment by kif** [comment]
Apparently you have spotted a bug when it comes to inverse Angstroms instead of inverse nanometer. The 10x scale difference is in the wrong directio. my bad.

**Comment by kif** [comment]
Apparently you have spotted a bug when it comes to inverse Angstroms instead of inverse nanometer. The 10x scale difference is in the wrong direction. my bad.

Nota:
For integrating all available azimuthal angle, don't specify the azimuthal range. forcing 0-360 is likely to crop the region from -pi to 0 and keep only the region from 0 to pi (unless you have configured your intergration to work in another way around, from 0 to 2pi.

**Comment by kif** [comment]
Here is the tutorial.
https://github.com/kif/pyFAI/blob/master/doc/source/usage/tutorial/LogScale/Guinier.ipynb

The fix are under review for integration in the development branch.

**Comment by Miradin** [comment]
Hello, Jerome.
great tutorial, that helped a lot. I've fixed scale for "arcsinh(q.A)_None" and "log(1+q.A)_None" units.
Will azimuthal range be full if I specify range 0-359.5?
I think we can close this issue.

Regards,
Alexander

**Comment by kif** [comment]
If you want the full range, don't specify the range. It will not select pixels on this criteria (i.e. take the all).

If you want to restrict, the numerical value has to be in radians (because internals of pyFAI are in radians) and may depend on the discontinuity position (by default pi) and on the rot3 parameter which correspond to the rotation around the beam (rot3=0 most of the time). So everything correspond to (-pi, pi).

**Comment by Miradin** [comment]
Hello Jerome,
sorry for rising a question here again, but could you comment on modified version of your tutorial?

[it is here](https://github.com/Miradin/test-debug/blob/master/Guinier.ipynb)

I have changed the range in section "Selection of the log-space rebinning" to be more close to SAXS region. Now it is visible that behavior of functions arcsinh and log1p are very close to linear and does not match log10. In section "Effect of radial_range" the difference in chosen binning function is almost negligible.

Could you also comment huge q-range extension in section "Unexpected behavior"?

With best regards,
Alexander

**Comment by kif** [comment]
Hi Alexander,
I checked your code and it behaves properly ... on my computer.
I suspect it is either related to python2 (old compiler) or a 32 bit installation 

Could you please give me the value returned by this on you python ?
tuple.__itemsize__

Thanks

**Comment by Miradin** [comment]
Hello Jerome,
I have Python 3.6.4 installed on 64-bit Windows 7.
tuple.__itemsize__ returns 8
pyFAI version 0.15.0
numpy version 1.14.4

Best regards,
Alexander
